Repository UCF/unify-events, pull requests merged in 2020-12, with the labels that each got.

#57 Add Virtual Location option/field and updates for location functionality
  events/forms/manager.py
  events/migrations/0004_eventinstance_virtual_url.py
  events/models/event.py
  static_files/assets/js/script-manager.js
  static_files/assets/scss/_forms.scss
  static_files/assets/scss/_views-backend.scss
  static_files/assets/scss/_views-frontend.scss
  static_files/static/css/style.min.css
  static_files/static/js/script-manager.min.js
  templates/esi/eventinstance/listing.html
  templates/events/frontend/event-single/event.html
  templates/events/manager/events/create_update.html
  templates/events/manager/events/instance_create_update.html
Labels: Enhancement

#58 Active Calendars
  events/forms/manager.py
  events/management/commands/audit-calendars.py
  events/migrations/0005_calendar_active.py
  events/models/calendar.py
  events/models/event.py
  events/views/manager/calendar.py
  events/views/manager/event.py
  events/views/manager/search.py
  events/views/search.py
  static_files/assets/scss/_forms.scss
  static_files/static/css/style.min.css
  templates/events/manager/calendar/update.html
  templates/events/manager/dashboard.html
Labels: Enhancement

#62 Update single event templates for feeds to include virtual location data
  templates/events/frontend/event-single/event.ics
  templates/events/frontend/event-single/event.json
  templates/events/frontend/event-single/event.rss
  templates/events/frontend/event-single/event.xml
Labels: Enhancement

#65 Update gaEventTracking function so that target attribute is respected
  static_files/assets/js/script.js
  static_files/static/js/script.min.js
Labels: Bug

#64 Add location icons to single event and listing view
  static_files/assets/scss/_views-frontend.scss
  static_files/static/css/style.min.css
  templates/.editorconfig
  templates/esi/eventinstance/listing.html
  templates/events/frontend/event-single/event.html
Labels: Enhancement

#66 Documentation Updates for Virtual Location
  static_files/static/img/help-screenshots/create-event-location-create.gif
  static_files/static/img/help-screenshots/create-event-location-select.gif
  static_files/static/img/help-screenshots/create-event-virtual-location.gif
  templates/events/static/help.html
Labels: documentation

#67 Empty locations
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
Labels: Bug, Enhancement
