Repository UCF/unify-events, pull requests merged in 2021-02, with the labels that each got.

#73 Added logic for redirecting tags not found
  events/views/event_views.py
Labels: Enhancement

#72 Calendar select2
  events/urls/manager.py
  events/views/manager/search.py
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
  templates/events/manager/base.html
  templates/events/manager/events/create_update.html
Labels: Enhancement

#77 Added logic to redirect not found calendars
  events/views/event_views.py
Labels: Enhancement

#79 Tag typeahead scoring
  events/forms/manager.py
  events/migrations/0006_auto_20210204_1416.py
  events/models/event.py
  events/urls/manager.py
  events/views/manager/search.py
  events/views/manager/tag.py
  templates/events/manager/tag/list.html
Labels: Enhancement

#81 Added tags to search
  events/views/search.py
Labels: Bug, Enhancement

#83 Added migration that removes the through error
  events/migrations/0007_auto_20210208_1157.py
Labels: Bug

#84 Typeahead replacement
  package-lock.json
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_typeahead.scss
  static_files/static/css/style-backend.min.css
  static_files/static/css/style.min.css
  static_files/static/fonts/fontawesome/fa-brands-400.eot
  static_files/static/fonts/fontawesome/fa-brands-400.svg
  static_files/static/fonts/fontawesome/fa-brands-400.ttf
  static_files/static/fonts/fontawesome/fa-brands-400.woff
  static_files/static/fonts/fontawesome/fa-brands-400.woff2
  static_files/static/fonts/fontawesome/fa-regular-400.eot
  static_files/static/fonts/fontawesome/fa-regular-400.svg
  static_files/static/fonts/fontawesome/fa-regular-400.ttf
  static_files/static/fonts/fontawesome/fa-regular-400.woff
  static_files/static/fonts/fontawesome/fa-regular-400.woff2
  static_files/static/fonts/fontawesome/fa-solid-900.eot
  static_files/static/fonts/fontawesome/fa-solid-900.svg
  static_files/static/fonts/fontawesome/fa-solid-900.ttf
  static_files/static/fonts/fontawesome/fa-solid-900.woff
  static_files/static/fonts/fontawesome/fa-solid-900.woff2
  static_files/static/js/script-manager.min.js
  templates/events/manager/base.html
  templates/events/manager/events/create_update.html
Labels: Bug

#85 Athena table fixes
  static_files/assets/scss/components/_manager-tables.scss
  static_files/assets/scss/style.scss
  static_files/static/css/style.min.css
  templates/events/manager/calendar/list.html
  templates/events/manager/calendar/update/update-subscriptions.html
  templates/events/manager/calendar/update/update-users.html
  templates/events/manager/category/list.html
  templates/events/manager/location/list.html
  templates/events/manager/profiles/list.html
  templates/events/manager/tag/list.html
Labels: Enhancement

#87 Event create/update tag styles updates
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_event-create-update.scss
  static_files/static/css/style-backend.min.css
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
Labels: Enhancement

#86 Small Updates
  README.md
  gulpfile.js
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_select2.scss
  static_files/assets/scss/style-backend.scss
  static_files/static/css/style-backend.min.css
  static_files/static/img/help-screenshots/create-event-btn.gif
  static_files/static/img/help-screenshots/create-event-btn.jpg
  static_files/static/img/help-screenshots/create-event-desc.gif
  static_files/static/img/help-screenshots/create-event-virtual-location.gif
  static_files/static/js/script-manager.min.js
  static_files/static/js/wysiwyg/plugins/lists/index.js
  static_files/static/js/wysiwyg/plugins/lists/plugin.js
  static_files/static/js/wysiwyg/plugins/lists/plugin.min.js
  templates/esi/template/navbar.html
  templates/events/manager/calendar/update/update-users.html
  templates/events/static/help.html
Labels: Bug, Enhancement

#88 Location typeahead
  events/forms/manager.py
  events/templatetags/locations.py
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_event-create-update.scss
  static_files/assets/scss/components/_typeahead.scss
  static_files/static/css/style-backend.min.css
  static_files/static/css/style.min.css
  static_files/static/fonts/fontawesome/fa-brands-400.eot
  static_files/static/fonts/fontawesome/fa-brands-400.svg
  static_files/static/fonts/fontawesome/fa-brands-400.ttf
  static_files/static/fonts/fontawesome/fa-brands-400.woff
  static_files/static/fonts/fontawesome/fa-brands-400.woff2
  static_files/static/fonts/fontawesome/fa-regular-400.eot
  static_files/static/fonts/fontawesome/fa-regular-400.svg
  static_files/static/fonts/fontawesome/fa-regular-400.ttf
  static_files/static/fonts/fontawesome/fa-regular-400.woff
  static_files/static/fonts/fontawesome/fa-regular-400.woff2
  static_files/static/fonts/fontawesome/fa-solid-900.eot
  static_files/static/fonts/fontawesome/fa-solid-900.svg
  static_files/static/fonts/fontawesome/fa-solid-900.ttf
  static_files/static/fonts/fontawesome/fa-solid-900.woff
  static_files/static/fonts/fontawesome/fa-solid-900.woff2
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
  templates/events/manager/events/instance_create_update.html
Labels: Enhancement

#89 Typeahead touchups
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
Labels: Bug

#90 Adds Event Registration Functionality
  events/forms/manager.py
  events/migrations/0008_auto_20210211_1051.py
  events/models/event.py
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_event-create-update.scss
  static_files/assets/scss/components/_typeahead.scss
  static_files/static/css/style-backend.min.css
  static_files/static/js/script-manager.min.js
  templates/events/frontend/event-single/event.html
  templates/events/manager/events/create_update.html
Labels: Enhancement

#91 Added searching and filtering for the tag list view
  events/views/manager/tag.py
  templates/events/manager/tag/list.html
Labels: Enhancement

#93 Add Athena form validation markup
  templates/events/manager/calendar/create.html
  templates/events/manager/calendar/update.html
  templates/events/manager/category/create_update.html
  templates/events/manager/events/create_update.html
  templates/events/manager/events/instance_create_update.html
  templates/events/manager/firstlogin/calendar_create.html
  templates/events/manager/firstlogin/profile.html
  templates/events/manager/location/create_update.html
  templates/events/manager/login.html
  templates/events/manager/profiles/profile.html
  templates/events/manager/tag/create_update.html
Labels: Enhancement

#94 Added a keyup event to clear the new tag button
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
Labels: Bug

#95 Promoted Tags on Create/Update Event Form
  static_files/assets/js/script-manager.js
  static_files/assets/scss/components/_event-create-update.scss
  static_files/static/css/style-backend.min.css
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
Labels: Enhancement

#96 Image and Tag Documentation Updates
  static_files/static/img/help-screenshots/create-event-location-create.gif
  static_files/static/img/help-screenshots/create-event-location-select.gif
  static_files/static/img/help-screenshots/create-event-tags.gif
  templates/events/static/help.html
Labels: documentation

#98 Promoted Tag Fixes
  events/models/event.py
  events/views/manager/event.py
  events/views/manager/search.py
  package-lock.json
  package.json
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
Labels: Bug, Enhancement

#99 Support bulk posting of rereview events
  events/models/event.py
  events/views/manager/event.py
Labels: Enhancement

#100 Added location endpoint and updated logic
  events/urls/manager.py
  events/views/manager/event.py
  events/views/manager/search.py
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
  templates/events/manager/base.html
  templates/events/manager/events/create_update.html
Labels: Bug

#101 IE11 Compatibility
  package-lock.json
  package.json
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
Labels: Bug
