Repository UCF/unify-events, pull requests merged in 2022-09, with the labels that each got.

#155 Trusted Calendar Field
  events/forms/manager.py
  events/migrations/0009_calendar_trusted.py
  events/models/calendar.py
  static_files/static/js/wysiwyg/skins/lightgray/content.min.css
  templates/events/manager/calendar/list.html
  templates/events/manager/calendar/update.html
  templates/events/manager/dashboard.html
Labels: Enhancement

#160 Promotion model
  events/admin.py
  events/migrations/0010_promotion.py
  events/models/__init__.py
  events/models/promotion.py
  requirements.txt
Labels: Enhancement

#161 Promotion frontend
  events/views/event_views.py
  templates/esi/promotion/single.html
  templates/esi/template/promotion.html
  templates/events/frontend/calendar/calendar-type/calendar-default.html
  templates/events/frontend/event-single/event.html
  urls.py
Labels: Enhancement

#162 Promotion manager views
  events/forms/manager.py
  events/urls/manager.py
  events/views/manager/promotion.py
  templates/esi/template/navbar.html
  templates/events/manager/promotion/create.html
  templates/events/manager/promotion/delete.html
  templates/events/manager/promotion/list.html
  templates/events/manager/promotion/update.html
Labels: Enhancement

#163 Pending query
  events/utils.py
  events/views/manager/__init__.py
Labels: Bug

#165 Doc updates
  templates/events/static/help.html
Labels: documentation

#167 Added in new field descriptions with links to help sections
  templates/events/manager/events/create_update.html
Labels: Enhancement, documentation

#166 Event preview
  events/utils.py
  events/views/manager/event.py
  templates/events/frontend/event-single/event.html
  templates/events/manager/events/create_update.html
Labels: Enhancement

#168 Browser spellchecker
  events/forms/manager.py
  static_files/assets/js/script-manager.js
  static_files/static/js/script-manager.min.js
  templates/events/manager/events/create_update.html
Labels: Enhancement

#169 Added safe filter to description on event listings
  templates/esi/eventinstance/listing.html
Labels: Bug

#170 Add check for event state before showing publish button
  events/urls/manager.py
  events/views/manager/event.py
  templates/events/frontend/event-single/event.html
Labels: Bug
